# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sidebar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resource_rc  # Moved import to top-level

# Import custom widgets
from profile_widget import ProfileWidget
from aboutUs import AboutUsWidget  # Assuming filename is AboutUs.py
from setting import SettingsWidget  # Corrected import from 'setting' to 'settings'


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(832, 629)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.icon_only_widget = QtWidgets.QWidget(self.centralwidget)
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.icon_only_widget)
        self.label.setMinimumSize(QtCore.QSize(50, 50))
        self.label.setMaximumSize(QtCore.QSize(60, 60))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icon/icon/logo_icon.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.home_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.home_btn_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/home_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn_1.setIcon(icon)
        self.home_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.home_btn_1.setCheckable(True)
        self.home_btn_1.setAutoExclusive(True)
        self.home_btn_1.setObjectName("home_btn_1")
        self.verticalLayout.addWidget(self.home_btn_1)
        self.flash_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.flash_btn_1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/flashcard_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.flash_btn_1.setIcon(icon1)
        self.flash_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.flash_btn_1.setCheckable(True)
        self.flash_btn_1.setAutoExclusive(True)
        self.flash_btn_1.setObjectName("flash_btn_1")
        self.verticalLayout.addWidget(self.flash_btn_1)
        self.quizze_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.quizze_btn_1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/quizzes_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quizze_btn_1.setIcon(icon2)
        self.quizze_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.quizze_btn_1.setCheckable(True)
        self.quizze_btn_1.setAutoExclusive(True)
        self.quizze_btn_1.setObjectName("quizze_btn_1")
        self.verticalLayout.addWidget(self.quizze_btn_1)
        self.about_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.about_btn_1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon/aboutus_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.about_btn_1.setIcon(icon3)
        self.about_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.about_btn_1.setCheckable(True)
        self.about_btn_1.setAutoExclusive(True)
        self.about_btn_1.setObjectName("about_btn_1")
        self.verticalLayout.addWidget(self.about_btn_1)
        self.setting_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.setting_1.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon/setting_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setting_1.setIcon(icon4)
        self.setting_1.setIconSize(QtCore.QSize(20, 20))
        self.setting_1.setCheckable(True)  # Re-enabled
        self.setting_1.setAutoExclusive(True)  # Re-enabled
        self.setting_1.setObjectName("setting_1")
        self.verticalLayout.addWidget(self.setting_1)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 262, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.logout_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.logout_btn_1.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icon/logout_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logout_btn_1.setIcon(icon5)
        self.logout_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.logout_btn_1.setCheckable(True)
        self.logout_btn_1.setAutoExclusive(True)
        self.logout_btn_1.setObjectName("logout_btn_1")
        self.verticalLayout_3.addWidget(self.logout_btn_1)
        self.gridLayout.addWidget(self.icon_only_widget, 0, 0, 1, 1)
        self.full_mwnu_widget = QtWidgets.QWidget(self.centralwidget)
        self.full_mwnu_widget.setObjectName("full_mwnu_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.full_mwnu_widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.full_mwnu_widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.home_btn_2 = QtWidgets.QPushButton(self.full_mwnu_widget)
        self.home_btn_2.setCheckable(True)
        self.home_btn_2.setAutoExclusive(True)
        self.home_btn_2.setObjectName("home_btn_2")
        self.verticalLayout_2.addWidget(self.home_btn_2)
        self.flash_btn_2 = QtWidgets.QPushButton(self.full_mwnu_widget)
        self.flash_btn_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/flashcard_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.flash_btn_2.setIcon(icon1)
        self.flash_btn_2.setIconSize(QtCore.QSize(20, 20))
        self.flash_btn_2.setCheckable(True)
        self.flash_btn_2.setAutoExclusive(True)
        self.flash_btn_2.setObjectName("flash_btn_2")
        self.verticalLayout_2.addWidget(self.flash_btn_2)
        self.quizze_btn_2 = QtWidgets.QPushButton(self.full_mwnu_widget)
        self.quizze_btn_2.setCheckable(True)
        self.quizze_btn_2.setAutoExclusive(True)
        self.quizze_btn_2.setObjectName("quizze_btn_2")
        self.verticalLayout_2.addWidget(self.quizze_btn_2)
        self.about_btn_2 = QtWidgets.QPushButton(self.full_mwnu_widget)
        self.about_btn_2.setCheckable(True)
        self.about_btn_2.setAutoExclusive(True)
        self.about_btn_2.setObjectName("about_btn_2")
        self.verticalLayout_2.addWidget(self.about_btn_2)
        self.setting_2 = QtWidgets.QPushButton(self.full_mwnu_widget)
        self.setting_2.setText("")  # This was missing text, added in retranslateUi
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon/setting_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setting_2.setIcon(icon4)
        self.setting_2.setIconSize(QtCore.QSize(20, 20))
        self.setting_2.setCheckable(True)  # Re-enabled
        self.setting_2.setAutoExclusive(True)  # Re-enabled
        self.setting_2.setObjectName("setting_2")
        self.verticalLayout_2.addWidget(self.setting_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 295, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.logout_btn_2 = QtWidgets.QPushButton(self.full_mwnu_widget)
        self.logout_btn_2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icon/logout_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logout_btn_2.setIcon(icon5)
        self.logout_btn_2.setIconSize(QtCore.QSize(20, 20))
        self.logout_btn_2.setCheckable(True)
        self.logout_btn_2.setAutoExclusive(True)
        self.logout_btn_2.setObjectName("logout_btn_2")
        self.verticalLayout_4.addWidget(self.logout_btn_2)
        self.gridLayout.addWidget(self.full_mwnu_widget, 0, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(self.widget_3)
        self.widget.setMinimumSize(QtCore.QSize(0, 40))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")

        # --- Reordered elements to place search at the top-left ---
        self.change_btn = QtWidgets.QPushButton(self.widget)
        self.change_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/icon/menu_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_btn.setIcon(icon6)
        self.change_btn.setIconSize(QtCore.QSize(25, 25))
        self.change_btn.setCheckable(True)
        self.change_btn.setObjectName("change_btn")
        self.horizontalLayout_4.addWidget(self.change_btn)

        # Search input and button
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_input = QtWidgets.QLineEdit(self.widget)
        self.search_input.setObjectName("search_input")
        self.horizontalLayout.addWidget(self.search_input)
        self.search_btn = QtWidgets.QPushButton(self.widget)
        self.search_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/icon/search_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_btn.setIcon(icon7)
        self.search_btn.setIconSize(QtCore.QSize(20, 20))
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout.addWidget(self.search_btn)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)  # Add the search layout here

        # Expanding spacer to push the user button to the right
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)

        # Label to display username
        self.username_display_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.username_display_label.setFont(font)
        self.username_display_label.setStyleSheet("color: #333;")  # Simple styling
        self.username_display_label.setObjectName("username_display_label")
        self.horizontalLayout_4.addWidget(self.username_display_label)

        self.user_btn = QtWidgets.QPushButton(self.widget)
        self.user_btn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/icon/person_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.user_btn.setIcon(icon8)
        self.user_btn.setIconSize(QtCore.QSize(25, 25))
        self.user_btn.setObjectName("user_btn")
        self.horizontalLayout_4.addWidget(self.user_btn)
        # --- End of reordered elements ---

        self.verticalLayout_5.addWidget(self.widget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setObjectName("stackedWidget")

        # Page 0: Home Page (self.page)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)

        # Page 1: Profile Page (self.page_7) - Now using ProfileWidget
        self.page_7 = ProfileWidget()  # Instantiate your custom ProfileWidget
        self.page_7.setObjectName("page_7")  # Keep the object name for consistency
        self.stackedWidget.addWidget(self.page_7)

        # Page 2: Flashcard Page (self.page_2)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)

        # Page 3: Quizze Page (self.page_3)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.PreventContextMenu)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)

        # Page 4: About us Page (self.page_4) - Now using AboutUsWidget
        self.page_4 = AboutUsWidget()  # Changed from QtWidgets.QWidget() to AboutUsWidget()
        self.page_4.setObjectName("page_4")  # Keep the object name for consistency
        self.stackedWidget.addWidget(self.page_4)

        # Page 5: Settings Page (self.page_5) - Now using SettingsWidget
        self.page_5 = SettingsWidget()  # New: Instantiate your custom SettingsWidget
        self.page_5.setObjectName("page_5")  # Keep the object name for consistency
        self.stackedWidget.addWidget(self.page_5)

        # Page 6: Search Page (self.page_6)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_9 = QtWidgets.QLabel(self.page_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_6)

        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.widget_3, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        # Connect the search button to the search_button_clicked method
        self.search_btn.clicked.connect(self.search_button_clicked)

        # Set initial page. If you want Home to be default, change to 0.
        self.stackedWidget.setCurrentIndex(0)  # Changed to Home Page as default

        # Connect sidebar buttons to switch stackedWidget pages
        self.home_btn_1.toggled['bool'].connect(
            lambda checked: self.stackedWidget.setCurrentIndex(0) if checked else None)
        self.home_btn_2.toggled['bool'].connect(
            lambda checked: self.stackedWidget.setCurrentIndex(0) if checked else None)

        self.flash_btn_1.toggled['bool'].connect(
            lambda checked: self.stackedWidget.setCurrentIndex(2) if checked else None)
        self.flash_btn_2.toggled['bool'].connect(
            lambda checked: self.stackedWidget.setCurrentIndex(2) if checked else None)

        self.quizze_btn_1.toggled['bool'].connect(
            lambda checked: self.stackedWidget.setCurrentIndex(3) if checked else None)
        self.quizze_btn_2.toggled['bool'].connect(
            lambda checked: self.stackedWidget.setCurrentIndex(3) if checked else None)

        # About Us button connections are now for AboutUsWidget
        self.about_btn_1.toggled['bool'].connect(
            lambda checked: self.stackedWidget.setCurrentIndex(4) if checked else None)
        self.about_btn_2.toggled['bool'].connect(
            lambda checked: self.stackedWidget.setCurrentIndex(4) if checked else None)

        # Settings button connections are now handled by main.py (via .clicked signal)
        self.setting_1.toggled['bool'].connect(
            lambda checked: self.stackedWidget.setCurrentIndex(5) if checked else None)  # Re-enabled
        self.setting_2.toggled['bool'].connect(
            lambda checked: self.stackedWidget.setCurrentIndex(5) if checked else None)  # Re-enabled

        # Connect user_btn to Profile Page (index 1)
        self.user_btn.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1))

        # Connect toggle buttons for sidebar visibility
        self.change_btn.toggled['bool'].connect(self.icon_only_widget.setVisible)  # type: ignore
        self.change_btn.toggled['bool'].connect(self.full_mwnu_widget.setHidden)  # type: ignore

        # Ensure mutual exclusivity for sidebar buttons (already there, but good to check)
        self.setting_1.toggled['bool'].connect(self.setting_2.setChecked)  # Re-enabled
        self.about_btn_1.toggled['bool'].connect(self.about_btn_2.setChecked)  # type: ignore
        self.quizze_btn_1.toggled['bool'].connect(self.quizze_btn_2.setChecked)  # type: ignore
        self.flash_btn_1.toggled['bool'].connect(self.flash_btn_2.setChecked)  # type: ignore
        self.home_btn_1.toggled['bool'].connect(self.home_btn_2.setChecked)  # type: ignore
        self.flash_btn_2.toggled['bool'].connect(self.flash_btn_1.setChecked)  # type: ignore
        self.quizze_btn_2.toggled['bool'].connect(self.quizze_btn_1.setChecked)  # type: ignore
        self.about_btn_2.toggled['bool'].connect(self.about_btn_1.setChecked)  # type: ignore
        self.setting_2.toggled['bool'].connect(self.setting_1.setChecked)  # Re-enabled

        self.logout_btn_2.clicked.connect(MainWindow.close)  # type: ignore
        self.logout_btn_1.clicked.connect(MainWindow.close)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Set the username display label text to a default. main.py will update this.
        self.username_display_label.setText("Welcome!")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Sidebar"))
        self.home_btn_2.setText(_translate("MainWindow", "Home"))
        self.flash_btn_2.setText(_translate("MainWindow", "Flashcard"))
        self.quizze_btn_2.setText(_translate("MainWindow", "Quizze"))
        self.about_btn_2.setText(_translate("MainWindow", "About Us"))  # Keep button text
        self.setting_2.setText(_translate("MainWindow", "Settings"))  # Added text to setting_2
        self.logout_btn_2.setText(_translate("MainWindow", "Logout"))
        self.search_input.setPlaceholderText(_translate("MainWindow", "search......."))
        # Labels for pages - these are just text labels, the actual page content is in the stackedWidget
        self.label_4.setText(_translate("MainWindow", "Home Page"))
        self.label_5.setText(_translate("MainWindow", " Flashcard Page"))
        self.label_6.setText(_translate("MainWindow", "Quizze Page"))
        # REMOVED: self.label_7.setText(_translate("MainWindow", "About us Page")) # This line is removed
        # REMOVED: self.label_8.setText(_translate("MainWindow", "Settings Page")) # This line is removed
        self.label_9.setText(_translate("MainWindow", "Search Page"))
        # REMOVED: self.label_10.setText(_translate("MainWindow", "Profile Page")) # Removed this problematic line

    # New method to handle search button click - CORRECTLY INDENTED
    def search_button_clicked(self):
        search_query = self.search_input.text().strip().lower()  # Get text, strip whitespace, convert to lowercase
        print(f"Search button clicked! Query: '{search_query}'")

        # Map search queries to stackedWidget indices based on the order they are added in setupUi
        # Index 0: self.page (Home Page)
        # Index 1: self.page_7 (Profile Page - now ProfileWidget)
        # Index 2: self.page_2 (Flashcard Page)
        # Index 3: self.page_3 (Quizze Page)
        # Index 4: self.page_4 (About us Page - now AboutUsWidget)
        # Index 5: self.page_5 (Settings Page - now SettingsWidget)
        # Index 6: self.page_6 (Search Page)

        if search_query == "home":
            self.stackedWidget.setCurrentIndex(0)  # Home Page
        elif search_query == "profile":
            self.stackedWidget.setCurrentIndex(1)  # Profile Page
        elif search_query == "flashcard" or search_query == "flashcards":
            self.stackedWidget.setCurrentIndex(2)  # Flashcard Page
        elif search_query == "quizze" or search_query == "quizzes":
            self.stackedWidget.setCurrentIndex(3)  # Quizze Page
        elif search_query == "about us" or search_query == "about":  # About Us search condition is back
            self.stackedWidget.setCurrentIndex(4)  # About us Page
        elif search_query == "settings" or search_query == "setting":
            self.stackedWidget.setCurrentIndex(5)  # Settings Page
        else:
            # Default to Search Page for any other query
            self.stackedWidget.setCurrentIndex(6)  # Search Page
            # You might want to pass the query to the search page here if it has a display method
            # e.g., if self.page_6 had a method like set_search_query, call it here.
            # For example: self.page_6.findChild(QtWidgets.QLabel, "label_9").setText(f"Search Results for: '{search_query}'")

        self.search_input.clear()  # Clear the search input after searching

    # Added set_username_display method for main.py to call
    def set_username_display(self, username):
        """Sets the text of the username display label."""
        if self.username_display_label:
            self.username_display_label.setText(f"Welcome, {username}!")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
